### ISSUE TITLE
500 Internal server error on save

### ISSUE THREAD

**Issue by collinsauve** [jrusbatch/compilify#65] opened 2013-02-07 21:16 UTC
Whenever I save today, I get a 500.
This seems to be regardless of content - even the default content throws a 500.

**Comment by jrusbatch** [comment] 2013-02-08 23:15
This appears to have been caused by an upgrade performed by MongoHQ that broke compatibility with the version of mongocsharpdriver installed.

**Comment by jrusbatch** [comment] 2013-02-28 00:58
Fixed in 8c2e1e95253a732512e2dcfe31b08099a183bf3a.

**Closed as completed by jrusbatch** 2013-02-28 00:58 UTC
